### ISSUE TITLE
/Volumes/Homeshare/Xcode/anymacos/upload/ doesn't exist

### ISSUE THREAD

**Issue by perez987** [MacThings/anymacos#6]
Good night. I get the error `/Volumes/Homeshare/Xcode/anymacos/upload/ doesn't exist` when building the project.

I think it's caused by the line

```
cp /Users/luigi/Documents/Xcode/anymacos/ANYmacOS/anymacos.html
         /Volumes/Homeshare/Xcode/anymacos/upload/
```

in Target -> Build Phases -> Zip app and send to Homeshare.

Commenting this line, all works fine.

Thanks for your work.

**Comment by MacThings** [comment]
Hello.

Yes you are right. I should insert an If Condition to prevent these Error on other Systems.

Greetz
