### ISSUE TITLE
Installer errors happen constantly

### ISSUE THREAD

**Issue by adjustGirl** [MacThings/anymacos#7]
![anymac](https://github.com/user-attachments/assets/9c60cb9d-3ceb-4fba-b69e-6823aac89ee9)

Every downloads okay, but Installer errors happen constantly. What's wrong?

**Comment by MacThings** [comment]
Check the Box "Logfile", run and upload these log. But remove your password(s) from the log before.

**Comment by AlfredTe** [comment]
Does not work anymore!!!

Tested on iMac 2019 and MacBook Air M3!!!

**Comment by SchneHa** [comment]
[anymacos.txt](https://github.com/user-attachments/files/17591509/anymacos.txt)

**Comment by adjustGirl** [comment]
Too complicated. Used another option.

**Comment by SchneHa** [comment]
This issue isn‘t completed as it exists further. Please look at the logfile and tell us what to do.
